baseURL = "https://deqinglv.github.io/blog/"
languageCode = "en-us"
title = "山的下午茶"
theme = "github-style"
publishDir = "docs"
pygmentsCodeFences = true
pygmentsUseClasses = true




[params]
  author = "Deqing Lv"
  description = "Alibaba Software Engineer"
  github = "deqinglv"
  email = "deqing.ldq@gmail.com"
  utterances = "example/example.github.io"
  avatar = "https://avatars3.githubusercontent.com/u/6064297?s=460&u=59de91a71b664110669fa87ad15110e12e3250ad&v=4"
  url = "https://deqinglv.github.io/blog/"
  keywords = "blog, Deqing, Deqing Lv, google analytics"
  headerIcon = "images/github-mark-white.png"
  lastmod = true
  enableSearch = true


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]


[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false